version: '3.8'

services:
  chatbot:
    build: .
    container_name: chatbot_hotel_merecure
    ports:
      - "8010:8002"
    environment:
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE_NAME=${EVOLUTION_INSTANCE_NAME}
      - PROFESSIONAL_PHONE=${PROFESSIONAL_PHONE}
      - HOST=0.0.0.0
      - PORT=8002
      - DEBUG=False
    restart: unless-stopped
